name: Scrape

on:
  push:
    paths:
      - dist/index.js
      - data/**/errors.json
  schedule:
    # At minute 42 past every 2nd hour.
    - cron: 42 */2 * * *

jobs:
  Scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Scrape
        uses: ./
        with:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_PUBLIC_CHAT_ID: ${{ secrets.TELEGRAM_PUBLIC_CHAT_ID }}
          TELEGRAM_PRIVATE_CHAT_ID: ${{ secrets.TELEGRAM_PRIVATE_CHAT_ID }}

      # https://github.com/marketplace/actions/add-commit
      - name: Commit
        uses: EndBug/add-and-commit@v9
        if: ${{ always() && github.ref == 'refs/heads/main' }}
        with:
          add: data
          message: Commit scrape results
